version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "javiertuya" 
    open-pull-requests-limit: 20

  - package-ecosystem: nuget
    directory: "/client-netcore/"
    schedule:
      interval: daily
    assignees:
      - "javiertuya" 
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    assignees:
      - "javiertuya" 

  - package-ecosystem: docker
    directory: "/"
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    assignees:
      - "javiertuya" 
