version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    #avoids logback 1.4 to keep compatibility with java 8
    ignore:
      - dependency-name: "logback-classic"
        update-types: ["version-update:semver-minor"]
    schedule:
      interval: daily
    assignees:
      - "javiertuya" 
    open-pull-requests-limit: 20

  - package-ecosystem: nuget
    directory: "/client-netcore/"
    #RestSharp 107 includes breaking changes still not handled by openapi generator 6.0.0
    ignore:
      - dependency-name: "RestSharp"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
    assignees:
      - "javiertuya" 
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    assignees:
      - "javiertuya" 

  - package-ecosystem: docker
    directory: "/"
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    assignees:
      - "javiertuya" 
