version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

  - package-ecosystem: nuget
    directories: 
      - "/client-netcore/"
      - "/client-netstandard/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

  - package-ecosystem: docker
    directory: "/server-spring/"
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
